export const DEFAULT_COUNT = 5;
// export const API_HOST = process.env.REACT_APP_API_URL;
export const TAB_SIDE_BAR = {
  CHAT: 'CHAT',
  ROOM_CHAT: 'ROOM_CHAT',
  FRIEND: 'FRIEND',
  EVERYONE: 'EVERYONE',
  PROFILE: 'PROFILE',
  FRIEND_REQUESTS: 'FRIEND_REQUESTS'
};
